services:
  api:
      build:
        context: .
        dockerfile: app/database/docker/Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - db
      environment:
        - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/lieferando_db
        - PYTHONPATH=/app
      volumes:
        - .:/app
      command: ["uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]

  scraper:
    build:
      context: .
      dockerfile: app/scraper/docker/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/lieferando_db
      - PYTHONPATH=/app
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lieferando_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: